### ISSUE TITLE
How to remove firmware fast!

### ISSUE THREAD

**Issue by MasonQAQ** [fkie-cad/FACT_core#194]
when i delete a firmware the backend delete file for a long time ? why?

**Comment by jstucke** [comment]
At the moment, the delete firmware operation is split into single delete operations which are sent over the intercom indiviually. We are aware of the problem and want to address it at some point in the future.

**Comment by dorpvom** [comment]
In addition: You can also change a parameter in your config file to allow faster removal. I.e. the `ExpertSettings.intercom_poll_delay` defines the seconds between two deletions (among other things). You should be able to safely set this to say **0.1** (instead of **1.0**) to gain a speed up of 10 on the deletion time.
