### ISSUE TITLE
Missing Dictionary Entries

### ISSUE THREAD

**Issue by Qwerty0x64** [fkie-cad/FACT_core#243]
Hello,

I'm trying to develop a PlugIn which depends on printable_strings.

I came across a very weird behavior.

When I run the analysis with a "normal" firmware, everything is fine.
But when I purposely run the analysis with a zip file with custom binaries this happens:

The printable_strings analysis runs fine. The result is stored in the mongoDB.
But when I debug my code I can see in the runtime that file_object.processed_analysis['printable_strings'] has no 'strings' or 'offsets' element.

How can that be?

Thanks

(Screenshot of MongoDB and PyCharm Debugger)

![Screenshot from 2019-04-12 22-05-48](https://user-images.githubusercontent.com/22414069/56063523-d05cb380-5d6f-11e9-98de-7e329510f90d.png)
![Screenshot from 2019-04-12 22-09-23](https://user-images.githubusercontent.com/22414069/56063524-d05cb380-5d6f-11e9-8fa6-7591f66ad421.png)

**Comment by dorpvom** [comment]
Hi, the answer to your problem is found looking at the `skipped` entry. The file you are looking at in your debugger is blacklisted by the printable strings plugin.
Currently all files of types
- application/gzip
- application/x-7z-compressed
- application/x-tar
- application/x-xz
- application/zip

are skipped. These were chosen because compressed files generally do not produce usable results.
