### ISSUE TITLE
Can't terminate !!!

### ISSUE THREAD

**Issue by icytxw** [fkie-cad/FACT_core#323]
When I run the command with 
```sh
 ./start_all_installed_fact_components --debug
```
the ctrl+c command can not terminate the program.

**Comment by dorpvom** [comment]
Hi,
this can be due to a variety of reasons, though most trace back to a runtime error and a corresponding process not being able to be correctly terminated.

For clarification

a) Do you observe this being specifically the case with `--debug` activated?
b) Does this also occur directly (say 20 sec.) after starting the command or only after some analysis was run?
c) Can you observe any exceptions in the log?

**Comment by icytxw** [comment]
@dorpvom Hi, 
Yes, the case was specifically with ```--debug``` activate, and this still occur after 24hours. Only ``` ./start_all_installed_fact_components --debug``` command trigger this issue(```./start_all_installed_fact_components and ./start_fact_backend can terminate the program normally). Cause this is not a exceptions, just can't terminate the demon process, there is no exception in the log. Can't you trigger this issue in your machine?

**Comment by icytxw** [comment]
I know the reason now, the problem seems occur at function ```was_started_by_start_fac```t in  ```src/helperFunctions/program_setup.py```, which return false in function```start_fact_bactend``` when  called by ```start_all_installed_fact_components```

**Comment by dorpvom** [comment]
Hi, just as an update: We'll have a look at this tomorrow. So hopefully this will be fixed soon-ish.
