### ISSUE TITLE
How to stop a current firmware analysis

### ISSUE THREAD

**Issue by dsyman** [fkie-cad/FACT_core#438]
I wonder if I can stop a running analysis. I can I do it?

**Comment by dorpvom** [comment]
Unfortunetly not.
The running tasks, i.e. the firmware components are not directly linked to the firmware. We recently developed a solution for monitoring progress, this does not work for stopping though, since there are a number of edge cases that could badly impact other concurrenlty running analyses.
For the moment this can only be done by stopping the backend (or all of FACT if not run independently) and restarting it afterwards.

**Comment by dsyman** [comment]
Thank you
