### ISSUE TITLE
cwe_checker, cve_checker  rest api no data

### ISSUE THREAD

**Issue by logerrors** [fkie-cad/FACT_core#585]
hi, the webpage has data, but the restful api /rest/firm/<uid> no data.
latest version, 3.2 and ubuntu20.04
![image](https://user-images.githubusercontent.com/31824303/120339921-1e561c00-c328-11eb-8556-54df418b894f.png)
![image](https://user-images.githubusercontent.com/31824303/120340039-3cbc1780-c328-11eb-8641-49a19d309aa5.png)

**Comment by jstucke** [comment]
Hi, you need to set the URL parameter "summary" to `true` to get the summary (as documented [here](https://github.com/fkie-cad/FACT_core/wiki/Rest-API#get))

e.g. `curl 'http://localhost:5000/rest/firmware/{{uid}}?summary=true' -X GET`

The summary is not always included because it is dynamically generated from the analysis results of the individual included files (which can be costly and take a while for large firmware).

**Comment by logerrors** [comment]
thank you very much , i found it and solve this problem.
