### ISSUE TITLE
firmware <-> file compare view bug

### ISSUE THREAD

**Issue by weidenba** [fkie-cad/FACT_core#61]
Comparing a file to a firmware causes a broken view

**Comment by dorpvom** [comment]
Also, when navigating from the compare view to an analyzed object, if the parent is not a firmware, the analysis pages starts with:
**Analysis for _insufficient information: firmware analysis not complete_**
Since deciding which firmware might be the parent of the given file object is non trivial, there may have to be an entirely different solution for this.
