### ISSUE TITLE
how to enable and config authentication correctly

### ISSUE THREAD

**Issue by xc-chen3** [fkie-cad/FACT_core#766]
i just found "**authentication = false**" in  /src/config/main.cfg, and it's also said "# !!!! Do not edit below this line unless you know exactly what you are doing !!!!",  so how can i enable user authentication correctly, or just modify to  "**authentication = ture**", thanks.

**Comment by dorpvom** [comment]
Hi,

you can find an explanation to the authentication, how to enable, customize and use it [here](https://github.com/fkie-cad/FACT_core/wiki/Authentication). If you have further questions or something doesn't work for you please re-open this issue. Since it's been a while that someone has worked on that page, details might have changed.

Cheers.
