### ISSUE TITLE
3.2

### ISSUE THREAD

**Issue by waytai** [fkie-cad/FACT_core#783]
version 3.2
install success but can not use
I have change pymongo to pymongo==2.9.0

**Comment by jstucke** [comment]
Hi, we don't really have the resources to maintain old versions of FACT. Could you try using the [latest release version](https://github.com/fkie-cad/FACT_core/releases/tag/3.3.1) or the current master branch? If you cloned the repository with git, you can change the branch (`git checkout master`) inside your FACT folder and rerun the installation (`python3 src/install.py`).

If you downloaded FACT as an archive, you could download the newest release version and run the installation again. It should also be  possible to unpack it into an existing installation (overwriting the files) in order to not having to download/install everything again.
